version: '2'
services:
        showdoc:
                container_name: showdoc
                image: star7th/showdoc 
                ports:
                        - "8888:80"
                volumes:
                        - ./volumes/showdoc/data/html:/var/www/html

